{
  description = "rv — a jj-native terminal branch reviewer";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        # release-plz owns the version and writes it to one place; reading it back
        # is what keeps the store path from saying 1.0.0 forever. Not named
        # `cargo`: the dev shell below lists `cargo` under `with pkgs`, and a
        # `let` binding of that name shadows the package.
        manifest = builtins.fromTOML (builtins.readFile ./Cargo.toml);
      in
      {
        packages.default = pkgs.rustPlatform.buildRustPackage {
          pname = "rv";
          version = manifest.workspace.package.version;
          src = pkgs.lib.cleanSource ./.;
          cargoLock.lockFile = ./Cargo.lock;

          nativeBuildInputs = [ pkgs.makeWrapper pkgs.installShellFiles ];
          # difftastic is found on PATH at run time and degraded past gracefully,
          # but a nix-installed rv should not degrade for want of a wrapper.
          #
          # Completions before the wrap: `wrapProgram` moves the real binary
          # aside, and the scripts are generated by running it.
          postInstall = ''
            installShellCompletion --cmd rv \
              --bash <($out/bin/rv completions bash) \
              --fish <($out/bin/rv completions fish) \
              --zsh <($out/bin/rv completions zsh)

            wrapProgram $out/bin/rv \
              --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.difftastic ]}
          '';

          # The suite spawns a jj workspace per test and takes minutes; it runs
          # in the dev shell (`cargo test --workspace`), not in every build.
          doCheck = false;

          meta = {
            description = "A jj-native terminal branch reviewer";
            homepage = "https://github.com/Firaenix/rv";
            license = with pkgs.lib.licenses; [ mit asl20 ];
            mainProgram = "rv";
          };
        };

        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            cargo
            rustc
            rust-analyzer
            clippy
            rustfmt
            difftastic
            jujutsu
          ];
        };
      });
}
