//! The table itself: every key browse mode answers, one row each. `leader: None`
//! is a direct key; `leader: Some(_)` sits under that leader's which-key submenu,
//! its `codes` the *second* keystroke. Movement is arrows (and the mouse) only.

use crossterm::event::KeyCode;

use super::Binding;
use super::Command;
use super::Group;
use super::Leader;

/// Every key browse mode answers, and the **only** thing the browse handler
/// dispatches from, so the popup and the keyboard cannot drift. The order is the
/// order the popup reads in, grouped by [`Group`].
pub const BINDINGS: &[Binding] = &[
    Binding {
        keys: "↓",
        group: Group::Move,
        leader: None,
        what: "next row",
        codes: &[KeyCode::Down],
        command: Command::Forward,
    },
    Binding {
        keys: "↑",
        group: Group::Move,
        leader: None,
        what: "prev row",
        codes: &[KeyCode::Up],
        command: Command::Back,
    },
    Binding {
        keys: "←",
        group: Group::Focus,
        leader: None,
        what: "out / up",
        codes: &[KeyCode::Left],
        command: Command::FocusLeft,
    },
    Binding {
        keys: "→",
        group: Group::Focus,
        leader: None,
        what: "into / open",
        codes: &[KeyCode::Right],
        command: Command::FocusRight,
    },
    Binding {
        keys: "PgDn",
        group: Group::Scroll,
        leader: None,
        what: "page down",
        codes: &[KeyCode::PageDown],
        command: Command::PageForward,
    },
    Binding {
        keys: "PgUp",
        group: Group::Scroll,
        leader: None,
        what: "page up",
        codes: &[KeyCode::PageUp],
        command: Command::PageBackward,
    },
    Binding {
        keys: "Home",
        group: Group::Scroll,
        leader: None,
        what: "first row",
        codes: &[KeyCode::Home],
        command: Command::JumpFirst,
    },
    Binding {
        keys: "End",
        group: Group::Scroll,
        leader: None,
        what: "last row",
        codes: &[KeyCode::End],
        command: Command::JumpLast,
    },
    Binding {
        keys: "]",
        group: Group::Move,
        leader: None,
        what: "next file",
        codes: &[KeyCode::Char(']')],
        command: Command::NextFile,
    },
    Binding {
        keys: "[",
        group: Group::Move,
        leader: None,
        what: "previous file",
        codes: &[KeyCode::Char('[')],
        command: Command::PreviousFile,
    },
    Binding {
        keys: "Enter",
        group: Group::Focus,
        leader: None,
        what: "open / zoom in",
        codes: &[KeyCode::Enter],
        command: Command::Enter,
    },
    Binding {
        keys: "Tab",
        group: Group::Focus,
        leader: None,
        what: "tree / diff",
        codes: &[KeyCode::Tab],
        command: Command::ToggleFocus,
    },
    Binding {
        keys: "f",
        group: Group::Focus,
        leader: Some(Leader::Mode),
        what: "files",
        codes: &[KeyCode::Char('f')],
        command: Command::FilesTab,
    },
    Binding {
        keys: "c",
        group: Group::Focus,
        leader: Some(Leader::Mode),
        what: "commits",
        codes: &[KeyCode::Char('c')],
        command: Command::CommitsTab,
    },
    Binding {
        keys: "m",
        group: Group::Focus,
        leader: Some(Leader::Mode),
        what: "comments",
        codes: &[KeyCode::Char('m')],
        command: Command::CommentsTab,
    },
    Binding {
        keys: "d",
        group: Group::Focus,
        leader: Some(Leader::Mode),
        what: "diff",
        codes: &[KeyCode::Char('d')],
        command: Command::ModeDiff,
    },
    Binding {
        keys: "s",
        group: Group::View,
        leader: None,
        what: "fold",
        codes: &[KeyCode::Char('s')],
        command: Command::Fold,
    },
    Binding {
        keys: "E",
        group: Group::Edit,
        leader: None,
        what: "open in $EDITOR",
        codes: &[KeyCode::Char('E')],
        command: Command::OpenEditor,
    },
    Binding {
        keys: "Esc",
        group: Group::Focus,
        leader: None,
        what: "back out",
        codes: &[KeyCode::Esc],
        command: Command::Escape,
    },
    Binding {
        keys: "?",
        group: Group::View,
        leader: None,
        what: "all the keys",
        codes: &[KeyCode::Char('?')],
        command: Command::Help,
    },
    Binding {
        keys: "q",
        group: Group::Quit,
        leader: None,
        what: "quit the review",
        codes: &[KeyCode::Char('q')],
        command: Command::Quit,
    },
    // Goto holds only jumps with no direct key (Home/End and Shift+arrow cover the ends and scroll).
    Binding {
        keys: "↓",
        group: Group::Move,
        leader: Some(Leader::Goto),
        what: "next hunk",
        codes: &[KeyCode::Down],
        command: Command::NextHunk,
    },
    Binding {
        keys: "↑",
        group: Group::Move,
        leader: Some(Leader::Goto),
        what: "prev hunk",
        codes: &[KeyCode::Up],
        command: Command::PreviousHunk,
    },
    Binding {
        keys: "n",
        group: Group::Move,
        leader: Some(Leader::Goto),
        what: "next symbol",
        codes: &[KeyCode::Char('n')],
        command: Command::NextSymbol,
    },
    Binding {
        keys: "N",
        group: Group::Move,
        leader: Some(Leader::Goto),
        what: "prev symbol",
        codes: &[KeyCode::Char('N')],
        command: Command::PreviousSymbol,
    },
    Binding {
        keys: "/",
        group: Group::Move,
        leader: Some(Leader::Goto),
        what: "find a symbol",
        codes: &[KeyCode::Char('/')],
        command: Command::Pick,
    },
    Binding {
        keys: "c",
        group: Group::Comment,
        leader: Some(Leader::Comment),
        what: "write a comment",
        codes: &[KeyCode::Char('c')],
        command: Command::Comment,
    },
    Binding {
        keys: "d",
        group: Group::Comment,
        leader: Some(Leader::Comment),
        what: "delete comment",
        codes: &[KeyCode::Char('d')],
        command: Command::Delete,
    },
    Binding {
        keys: "r",
        group: Group::Comment,
        leader: Some(Leader::Comment),
        what: "resolve/reopen",
        codes: &[KeyCode::Char('r')],
        command: Command::Resolve,
    },
    Binding {
        keys: "a",
        group: Group::Comment,
        leader: Some(Leader::Comment),
        what: "abandon/reopen",
        codes: &[KeyCode::Char('a')],
        command: Command::Abandon,
    },
    Binding {
        keys: "f",
        group: Group::View,
        leader: Some(Leader::View),
        what: "full context",
        codes: &[KeyCode::Char('f')],
        command: Command::ToggleFullContext,
    },
    Binding {
        keys: "g",
        group: Group::View,
        leader: Some(Leader::View),
        what: "group sides",
        codes: &[KeyCode::Char('g')],
        command: Command::GroupDiff,
    },
    Binding {
        keys: "b",
        group: Group::View,
        leader: Some(Leader::View),
        what: "which side",
        codes: &[KeyCode::Char('b')],
        command: Command::BeforeAfter,
    },
    Binding {
        keys: "t",
        group: Group::View,
        leader: Some(Leader::View),
        what: "list / tree",
        codes: &[KeyCode::Char('t')],
        command: Command::ToggleTree,
    },
    Binding {
        keys: "o",
        group: Group::View,
        leader: Some(Leader::View),
        what: "order the files",
        codes: &[KeyCode::Char('o')],
        command: Command::CycleSort,
    },
    Binding {
        keys: "c",
        group: Group::View,
        leader: Some(Leader::View),
        what: "tint the names",
        codes: &[KeyCode::Char('c')],
        command: Command::ToggleTint,
    },
    Binding {
        keys: "#",
        group: Group::View,
        leader: Some(Leader::View),
        what: "show the counts",
        codes: &[KeyCode::Char('#')],
        command: Command::ToggleCounts,
    },
    Binding {
        keys: "z",
        group: Group::View,
        leader: Some(Leader::View),
        what: "hide sidebar",
        codes: &[KeyCode::Char('z')],
        command: Command::ToggleSidebar,
    },
    Binding {
        keys: "<",
        group: Group::View,
        leader: Some(Leader::View),
        what: "narrow sidebar",
        codes: &[KeyCode::Char('<')],
        command: Command::Narrower,
    },
    Binding {
        keys: ">",
        group: Group::View,
        leader: Some(Leader::View),
        what: "widen sidebar",
        codes: &[KeyCode::Char('>')],
        command: Command::Wider,
    },
    Binding {
        keys: "i",
        group: Group::View,
        leader: Some(Leader::View),
        what: "change details",
        codes: &[KeyCode::Char('i')],
        command: Command::Info,
    },
    Binding {
        keys: "r",
        group: Group::View,
        leader: Some(Leader::View),
        what: "refresh",
        codes: &[KeyCode::Char('r')],
        command: Command::Refresh,
    },
];
