//! The `v` (view) leader's bindings — the complete, stable list of display
//! toggles — split from [`super::table`] for the 400-line rule and concatenated
//! back into `BINDINGS` there.

use crossterm::event::KeyCode;

use super::Binding;
use super::Command;
use super::Group;
use super::Leader;

pub(super) const VIEW: [Binding; 12] = [
    Binding {
        keys: "f",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "context",
        codes: &[KeyCode::Char('f')],
        command: Command::ToggleFullContext,
    },
    Binding {
        keys: "g",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "group",
        codes: &[KeyCode::Char('g')],
        command: Command::GroupDiff,
    },
    Binding {
        keys: "b",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "side",
        codes: &[KeyCode::Char('b')],
        command: Command::BeforeAfter,
    },
    Binding {
        keys: "t",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "list / tree",
        codes: &[KeyCode::Char('t')],
        command: Command::ToggleTree,
    },
    Binding {
        keys: "o",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "order",
        codes: &[KeyCode::Char('o')],
        command: Command::CycleSort,
    },
    Binding {
        keys: "c",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "tint",
        codes: &[KeyCode::Char('c')],
        command: Command::ToggleTint,
    },
    Binding {
        keys: "#",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "counts",
        codes: &[KeyCode::Char('#')],
        command: Command::ToggleCounts,
    },
    Binding {
        keys: "z",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "sidebar",
        codes: &[KeyCode::Char('z')],
        command: Command::ToggleSidebar,
    },
    Binding {
        keys: "<",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "narrower",
        codes: &[KeyCode::Char('<')],
        command: Command::Narrower,
    },
    Binding {
        keys: ">",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "wider",
        codes: &[KeyCode::Char('>')],
        command: Command::Wider,
    },
    Binding {
        keys: "i",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "details",
        codes: &[KeyCode::Char('i')],
        command: Command::Info,
    },
    Binding {
        keys: "r",
        group: Group::View,
        leader: Some(Leader::View),
        contexts: &[],
        what: "refresh",
        codes: &[KeyCode::Char('r')],
        command: Command::Refresh,
    },
];

/// The `g` (goto) and `c` (comment) leaders' children, split from
/// [`super::table`] for length.
pub(super) const JUMPS: [Binding; 9] = [
    Binding {
        keys: "↓",
        group: Group::Move,
        leader: Some(Leader::Goto),
        contexts: &[],
        what: "next hunk",
        codes: &[KeyCode::Down],
        command: Command::NextHunk,
    },
    Binding {
        keys: "↑",
        group: Group::Move,
        leader: Some(Leader::Goto),
        contexts: &[],
        what: "prev hunk",
        codes: &[KeyCode::Up],
        command: Command::PreviousHunk,
    },
    Binding {
        keys: "n",
        group: Group::Move,
        leader: Some(Leader::Goto),
        contexts: &[],
        what: "next sym",
        codes: &[KeyCode::Char('n')],
        command: Command::NextSymbol,
    },
    Binding {
        keys: "N",
        group: Group::Move,
        leader: Some(Leader::Goto),
        contexts: &[],
        what: "prev sym",
        codes: &[KeyCode::Char('N')],
        command: Command::PreviousSymbol,
    },
    Binding {
        keys: "/",
        group: Group::Move,
        leader: Some(Leader::Goto),
        contexts: &[],
        what: "find",
        codes: &[KeyCode::Char('/')],
        command: Command::Pick,
    },
    Binding {
        keys: "c",
        group: Group::Comment,
        leader: Some(Leader::Comment),
        contexts: &[],
        what: "write a comment",
        codes: &[KeyCode::Char('c')],
        command: Command::Comment,
    },
    Binding {
        keys: "d",
        group: Group::Comment,
        leader: Some(Leader::Comment),
        contexts: &[],
        what: "delete comment",
        codes: &[KeyCode::Char('d')],
        command: Command::Delete,
    },
    Binding {
        keys: "r",
        group: Group::Comment,
        leader: Some(Leader::Comment),
        contexts: &[],
        what: "resolve",
        codes: &[KeyCode::Char('r')],
        command: Command::Resolve,
    },
    Binding {
        keys: "a",
        group: Group::Comment,
        leader: Some(Leader::Comment),
        contexts: &[],
        what: "abandon",
        codes: &[KeyCode::Char('a')],
        command: Command::Abandon,
    },
];
